[fr]
  languageName = "ğŸ‡«ğŸ‡· FranÃ§ais"
  languageCode = "fr-FR"
  weight = 10
  [pt.params]
    languageISO = "FR"

[en]
  languageName = "ğŸ‡ºğŸ‡¸ English"
  languageCode = "en-US"
  weight = 20
  [en.params]
    languageISO = "EN"
